### ISSUE TITLE
xctool: command not found

### ISSUE THREAD

**Issue by tangqiaoboy** [Polidea/ios-class-guard#13]
Dear author,

When I ran the sample project, it reported the error message `xctool: command not found`.

I guess the `xctool` should be the tool from facebook (https://github.com/facebook/xctool), but facebook's xctool is a batch file, so it should be xctool.sh. 

Please help me, the detailed console log is below:

```
+ PROJECT=SWTableViewCell.xcodeproj
+ SCHEME=SWTableViewCell
+ TARGET=SWTableViewCell
+ CONFIGURATION=Release
+ SDK=iphoneos
+ git reset --hard
HEAD is now at 1d0469d Integrate iOS-Class-Guard
+ git clean -fdx
+ [[ -f Podfile ]]
+ xctool -project SWTableViewCell.xcodeproj -scheme SWTableViewCell -configuration Release -sdk iphoneos clean build OBJROOT=build/ SYMROOT=build/
obfuscate_project: line 19: xctool: command not found
```

**Comment by daushn** [comment]
Hello, I wanted to run the command ios-class-guard --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk, but nothing has changed.

**Comment by daushn** [comment]
Hello, I wanted to run the command:
 ios-class-guard --sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk 
But nothing has changed. Can you hel me?
