### ISSUE TITLE
Why NSObject isn't in forbidden list?

### ISSUE THREAD

**Issue by AloneMonkey** [Polidea/ios-class-guard#22]
Why NSObject isn't in forbidden list?

**Comment by AloneMonkey** [comment]
I define custom class ViewController that inherit from UIViewController。but the ios-class-guard will obfuscate funtion 'viewDidLoad'。this function is from UIViewController and shouldn't obfuscated。

like this:

#ifndef viewDidLoad
#define viewDidLoad z62
#endif // viewDidLoad

It shouldn't define in "symbols.h"。

**Comment by wiktor** [comment]
It is probably that SDK root path is wrongly set. Can you share you arguments to ios-class-guard?




Do you see while running tool following line?




`Processing external symbols from UIKit…`

**Comment by AloneMonkey** [comment]
yeah,  but when I run on the MAC, It can't find any function from UIKit and the offset of section is always 0.

Then I found that 'SDKroot/System/Library/Frameworks/UIKit.framework/UIKit' is just a symbols file. 

the real UIKit file in iphone device: /System/Library/Caches/com.apple.dyld/ , Idyld_decache it.

Get new UIKit instead of SDK root UIKit. It's run OK!

**Comment by AloneMonkey** [comment]
Static library also be obfuscated.

**Comment by ayufan** [comment]
This may also be problem with a Xcode 6.0/6.1. For that versions you need to compile an app for iOS Simulator.

**Comment by tgrf** [comment]
Try to obfuscate your project with the most recent version of `obfuscate_project` tool. We've changed SDK root to Simulator's one. As @ayufan said, since iOS SDK8 & Xcode 6, device's (iPhoneOS.platform) frameworks within Xcode files are just stubs.

**Comment by tgrf** [comment]
Closing this ticket, since it's fixed with the ```obfuscate_project``` script update (#23).
