### ISSUE TITLE
Unable to submit to AppStore

### ISSUE THREAD

**Issue by Ewg777** [Polidea/ios-class-guard#24]
![itunes](https://cloud.githubusercontent.com/assets/4364379/5998652/d5345ecc-aada-11e4-9fc5-5f670fce6bd1.png)

**Comment by wiktor** [comment]
Output of iso-class-guard is just simple header file with bunch of #defines. You might be adding to the app too much.

**Comment by ayufan** [comment]
`ptrace`?
