### ISSUE TITLE
xcodebuild: error: 'YourProject.xcodeproj' does not exist.

### ISSUE THREAD

**Issue by daushn** [Polidea/ios-class-guard#26]
git reset --hard
HEAD is now at 46bb94d 04.03.15 for obfuscate 2
git clean -fdx
xcodebuild -project YourProject.xcodeproj -scheme YourScheme -configuration Release -sdk iphonesimulator7.1 clean build -derivedDataPath build
User defaults from command line:
    IDEDerivedDataPathOverride = ....

Build settings from command line:
    SDKROOT = iphonesimulator7.1

xcodebuild: error: 'YourProject.xcodeproj' does not exist.
logout

**Comment by tgrf** [comment]
I assume, that you use `obfuscate_project` script, am I right? In that case, you have to provide proper values to variables corresponding to your project in the first section of the script and commit those changes.
```
#!/bin/bash

set -e

# General build options
# WORKSPACE=YourWorkspace.xcworkspace
PROJECT=YourProject.xcodeproj
SCHEME=YourScheme
CONFIGURATION=Release
SDK=7.1

# Additional build options
XCODEBUILD_OPTS=""
CLASS_GUARD_OPTS="-i IgnoredSymbol -F !ExcludedClass"

# In case of using Xcode >= 6 and SDK >= 8
CLASS_GUARD_OPTS_SDK="--sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator$SDK.sdk"
```

**Comment by daushn** [comment]
Thanks, I corrected, but that's got this error :

The following build commands failed:
	Ld build/Build/Intermediates/ATF24.build/Release-iphonesimulator/ATF24.build/Objects-normal/i386/ATF24 normal i386
	Ld build/Build/Intermediates/ATF24.build/Release-iphonesimulator/ATF24.build/Objects-normal/x86_64/ATF24 normal x86_64
(2 failures)
logout

**Comment by tgrf** [comment]
@daushn, there are some linker issues. If your project is compiling properly without obfuscation, check out what has been said in readme's section `Undefined symbols` (https://github.com/Polidea/ios-class-guard#undefined-symbols) of the iOS Class Guard project. Try to figure out which symbols are missing and exclude them from obfuscation.

**Comment by daushn** [comment]
Yes, it's compiling properly without obfuscation.

**Comment by daushn** [comment]
Guys please help me. Still shows this error:

**Comment by daushn** [comment]
Maybe it will be help for someone, finally I found a solution to this issue. I just changed the script and instead of using `SYMROOT=/build ` tried this `SYMROOT=$(PWD)/build `. It's setting the SYMROOT with a absolute paths.
``` 
xcodebuild \
    -workspace MyProject.xcworkspace \
    -scheme MyProject \
    -sdk iphonesimulator8.1 \
    -configuration Release \
    clean build \
    OBJROOT=$(PWD)/build \
    SYMROOT=$(PWD)/build
```
