### ISSUE TITLE
[HELP] obfuscate failed

### ISSUE THREAD

**Issue by thinkwing** [Polidea/ios-class-guard#34]
My app was terminated:
![7c271096-a474-44d5-b30f-553caa8dcfae](https://cloud.githubusercontent.com/assets/368345/7783441/469588de-0175-11e5-91fe-119e8a9d103a.png)

And this is my obfuscate_project file:
![69065066-80eb-4cff-a957-e1d5334e0386](https://cloud.githubusercontent.com/assets/368345/7783442/56e55610-0175-11e5-8c59-6f339aeb47b1.png)

What can I do?

**Comment by thinkwing** [comment]
Hello guys, really need your help for this issue, thanks！！！

**Comment by ayufan** [comment]
Can you check what SDKs you have installed?

**Comment by tgrf** [comment]
Could you please copy exception text, not image, here?

**Comment by thinkwing** [comment]
@ayufan  You are right, my mistake! Because of two versions (xcode5 & xcode6) I have installed, I got it wrong about the path of SDKs(xcode6). Now I have got a message "Congratulations! Obfuscation completed. You can now build, test and archive Your project using Xcode, Xctool or Xcodebuid...".

But when building, I got a message "/my_project_path/Pods/DTFoundation/Core/Source/DTHTMLParser/DTHTMLParser.m:10:9: 'libxml/HTMLparser.h' file not found". It's very strange, this project has built successfully without using ios-class-guard. For this case, I don't know in which part the problem occurs? What can I do?

**Comment by thinkwing** [comment]
@tgrf  Thank you for your reply!!! I've solved the problem,and Now I have got a message "Congratulations! Obfuscation completed. You can now build, test and archive Your project using Xcode, Xctool or Xcodebuid...".  But I got another problem, the details as mentioned the last message to ayufan.

**Comment by tgrf** [comment]
@thinkwing, as a fast workaround, try to exclude `HTML*` from obfuscation.
