### ISSUE TITLE
use the obfuscate_project, but outside the git.

### ISSUE THREAD

**Issue by renlix** [Polidea/ios-class-guard#43]
Hi. I want to use the obfuscate_project in my project, but outside the git.

    But when I run "./obfuscate_project" at the root of my project I get the error:
            "git reset --hard
            fatal: Not a git repository (or any of the parent directories): .git "

    It is possible?

**Comment by Wolf4** [comment]
To skip git cleaup stage you can open obfuscate_project and comment following rows:

    # Clean current workspace
    echo_and_run git reset --hard
    echo_and_run git clean -fdx

**Comment by renlix** [comment]
thank you for your help.

**Comment by robert-yi-jones** [comment]
It is better to use git to control your project version. Because every obfuscating might destroy your source code. Without git, it is really hard to recover. 
And, when you obfuscate an obfuscated project, it will create big trouble in storyboard or nib.
