### ISSUE TITLE
The result of the ".\obfuscate_project" is not expected.

### ISSUE THREAD

**Issue by renlix** [Polidea/ios-class-guard#45]
I run the command: ./obfuscate_project, the result is: "Congratulations! Obfuscation completed. You can now build, test and archive Your project using Xcode, Xctool or Xcodebuid..." so i open my xcode and click Product->Archive, i am exporting to ".IPA" the result file ".APP".
When open the file in the software "IDAQ" i can see all name of the  methods e other codes inside the file.
That result is the same when i build direct in xcode, whithout .\obfuscate_project
what i am making wrong ?

**Comment by robert-yi-jones** [comment]
In your project folder, you should see following extra folders and files after obfuscation.
/build
/build.obf
/symbols.h
/symbols.json
And, check your xxx-Prefix.pch, should have this line:
#import "/Users/<path>/<project name>/symbols.h"

If so, when you achieve or build your project, it is obfuscated.

-------------------P.S.--------------------
What is your XCode version? Because my XCode 7.0 doesn't work with ios-class-guard.

**Comment by renlix** [comment]
I am using Xcode 7.0.1

**Comment by robert-yi-jones** [comment]
Have you got any problem like " Unexpected '@' in program" when you compile your project?

**Comment by renlix** [comment]
Sorry for delayed answer, but i was curled up with other projects.

No, i do not got this error.  

I have got this error: "No code signing identities found", but i can building and generate Archive in my XCode, and the other projects I can  publishes them without problem.
I created a AppleID for my new test project in my MemberCenter and configured in my XCode project, bur when i run: "./obfuscate_project" i have got this error.

**Comment by renlix** [comment]
My error is because i changed "CLASS_GUARD_OPTS_SDK" from "iPhoneSimulator.platform" to "iPhoneOS.platform", when i backed,  i do not got more error.
But i can not find the file "symbols.h" nowhere.

**Comment by renlix** [comment]
Now i can run obfuscate_project without error, and generete "symbols.h".
When included "#import "/Users///symbols.h"" in my *-Prefix.h i have got error: "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:238:1: Unexpected '@' in program" and many other mistakes like this .

I did test in XCode 6 and work very well.

Anybody knows what i need make to work in XCode 7 iqual on XCode 6.
