### ISSUE TITLE
Can I obfuscate a Framework ?

### ISSUE THREAD

**Issue by renlix** [Polidea/ios-class-guard#47]
I developed a frameqork to use in my projects, and i'm need obfuscate this Framework.
Is it possible with command ./obfuscate_project ?

**Comment by robert-yi-jones** [comment]
I guess no.

**Comment by ayufan** [comment]
You can, but you need to exclude framework interface exposed to applications.

**Comment by renlix** [comment]
How i do this?
I need change something in the file "obfuscate_project" ?

**Comment by scibas** [comment]
You have to add all externally exposed methods of your framework to ignored symbols. You can achieve this by modifying  `obfuscate_project` script and adding your methods after `-i` parameter i.e. `-i myExternalMethod`

**Comment by renlix** [comment]
Thank you for your help, 
But I did not even get that part yet.

I can´t get any obfuscation.
I changed obfuscate_project in the lines:
    TARGET=$(basename "$app" .framework)
 and
    done < <(find build/ -name '*.framework')

I run the obfuscate_project, is generated the file symbols.h, this is imported in my *-Prefix.pch.

But the content of the file symbols.h is only this:
// Properties
// Protocols
// Classes
// Categories
// Methods
// I-vars

I have 1 file .m with methods ObjectiveC
And others much .cpp with methods c++.

What do i making wrong?

**Comment by junketjim** [comment]
Is this the same as #33 ?

**Comment by renlix** [comment]
Yes, it is.
Sorry me mistake, i don´t pay attention to #33.
Thank you for your help.

**Comment by RanaSaleh** [comment]
Hiii, please I want to apply obfuscation to my iOS framework but /PPiOS-Rename works for iOS 12 and above and my framework is available for iOS 10.0 and above , what can I do ? please
 advise .
