### ISSUE TITLE
I'm having trouble obfuscation.

### ISSUE THREAD

**Issue by renlix** [Polidea/ios-class-guard#48]
When i obfuscate my project, i have no error.
But when i run my project, only appears my screens UITableViewController, but my screens UIViewController  only appear black screen.

**Comment by scibas** [comment]
Hi renlix,
Could you provide more details?
- what Xcode version, what deployment target? 
- was `header.h` file generated?
- does your project contains any *pch file?

**Comment by renlix** [comment]
My Xcode is 6.4.
Yes, is generated the symbols.h.
Yes, my project have a file.pch, with #import ////symbols.
The obfuscation works well, it generates the necessary files, after that I can build my project and generate my App.
But when I run my App on the screens that are UIViewController not apacere nothing but a black screen.
I just solve it.
I added:
"- (void) loadView
{
     self.view = (UIView *) [[[NSBundle mainBundle] loadNibNamed:@"name my xib file" owner self options: nil] objectAtIndex: 0];
} "

Then went on to work normally.

Thank you very much.
