### ISSUE TITLE
Error when OBFUSCATE with SDK 11.0 XCode 9.0

### ISSUE THREAD

**Issue by renlix** [Polidea/ios-class-guard#64]
I updated my SDK to 11.0. When I OBFUSCATE my project and compiled, I get many errors with the phrases: "I expected an Objective-C directive after '@'", "Missing '@end'" and "Illegal interface qualifier."
Anyone have any idea why this?

**Comment by truist** [comment]
ios-class-guard hasn't been updated for iOS 11. You might want to try [PPiOS-Rename](https://github.com/preemptive/PPiOS-Rename) which is a fork of ios-class-guard that is maintained and has been updated for iOS 11. (I work for the company that makes PPiOS-Rename.)

**Comment by renlix** [comment]
Hello Nathan, I'm starting to use PPIOS-Rename according to you, but I'm facing some problems.
I run the commands: "ppios-rename --analyze -x IgnoredSymbol -F !ExcludedClass -F !FBS* -F !FIR* -F !ModalSMSCredito*  -F !GAI* -F !GGL* -F !Branch* /Desktop/Projetos/IOS/appPontoCerto//DerivedData/Build/Products/Debug-iphoneos/XXXXX.app" and "ppios-rename --obfuscate-sources".
But when I build my project, I get a lot of mistakes in relation to the 'FBSDK'(Facebook), 'FIRA'(Firebase), in my class 'ModalSMSCredito' and so on.
It is as if all the options "-F !YYY*" were ignored, and all were included in the obfuscation.

**Comment by neuralmer** [comment]
I have responded to this issue this [new thread](https://github.com/preemptive/PPiOS-Rename/issues/9).

**Comment by renlix** [comment]
Very good, thank you for your help.Naw woks fine.
Thamk you very much.
